Phi: 16.0
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_lr_multiplier: 0.5
beta: 5.0
center_lr_multiplier: 1.0
config_version: hyper1461_sub11_fit-human
from_logits: true
lr: 0.3
num_clusters: 8
num_repetitions: 16
num_subs: 23
q: 1
r: 2
random_seed: 999
specificity: 0.30000000000000004
temp1: equivalent
temp2: 0.6
thr: -0.45
trainable_specificity: false
unsup_rule: threshold
