Phi: 15.0
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_lr_multiplier: 0.2
beta: 2.0
center_lr_multiplier: 1.0
config_version: hyper47286_sustain-fullGD-newActvFunc-inhibition
from_logits: true
lr: 0.5
num_blocks: 32
num_clusters: 8
num_runs: 10
q: 1
r: 2
random_seed: 999
specificity: 0.1
thr: 999.0
trainable_specificity: false
unsup_rule: threshold
