Phi: 13.0
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_lr_multiplier: 5.0
beta: 4.5
center_lr_multiplier: 1.0
config_version: hyper3415_sub14_fit-human
from_logits: true
lr: 0.7
num_clusters: 8
num_repetitions: 16
num_subs: 23
q: 1
r: 2
random_seed: 999
specificity: 0.4
temp1: equivalent
temp2: 0.4
thr: -0.55
trainable_specificity: false
unsup_rule: threshold
