D: 5.0
actv_func: softmax
asso_lr_multiplier: 1.0
attn_lr_multiplier: 1.0
beta: 1.25
center_lr_multiplier: 1.0
config_version: hyper50_sustain-attn-asso-GD
from_logits: true
lr: 0.02
num_blocks: 32
num_clusters: 8
num_runs: 10
r: 7.0
random_seed: 999
thr: 999.0
unsup_rule: threshold
