Phi: 5.0
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: nonneg
attn_lr_multiplier: 0.5
beta: 1.25
center_lr_multiplier: 1.0
config_version: hyper3330_sustain-fullGD-newActvFunc
from_logits: true
lr: 0.05
num_blocks: 32
num_clusters: 8
num_runs: 10
q: 1
r: 2
random_seed: 999
specificity: 0.3
thr: 999.0
trainable_specificity: false
unsup_rule: threshold
