D: 10
actv_func: softmax
asso_lr_multiplier: 1
attn_lr_multiplier: 1
beta: 1.252233
center_lr_multiplier: 1
config_version: hyper0_CPU_sustain-center-attn-asso-GD
from_logits: true
lr: 0.05
num_blocks: 32
num_clusters: 8
num_runs: 50
r: 9.01245
random_seed: 999
thr: 999.0
unsup_rule: threshold