Phi: 5.0
actv_func: softmax
asso_lr_multiplier: 0.5
attn_constraint: nonneg
attn_lr_multiplier: 0.5
beta: 4.0
center_lr_multiplier: 1.0
config_version: hyper41843_sustain-fullGD-newActvFunc-inhibition
from_logits: true
lr: 0.3
num_blocks: 32
num_clusters: 8
num_runs: 10
q: 1
r: 2
random_seed: 999
specificity: 0.1
thr: 999.0
trainable_specificity: false
unsup_rule: threshold
