Phi: 10.0
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_lr_multiplier: 1.0
beta: 3.0
center_lr_multiplier: 1.0
config_version: hyper0_fit-human
from_logits: true
lr: 0.1
num_repetitions: 16      # one sequence of 8 stimuli in a fMRI run
num_clusters: 8
num_subs: 23             # independent top-level restarts of training
q: 1
r: 2
random_seed: 999
specificity: 0.25
temp1: equivalent
temp2: 0.012
thr: -0.4
trainable_specificity: false
unsup_rule: threshold
