Phi: 12.5
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_lr_multiplier: 1.0
beta: 1.5
center_lr_multiplier: 1.0
config_version: hyper11791_general
from_logits: true
lr: 0.1
num_blocks: 32
num_clusters: 8
num_runs: 10
q: 1
r: 2
random_seed: 999
specificity: 0.25
temp: 0.012
thr: -0.2
trainable_specificity: false
unsup_rule: threshold
