Phi: 19
actv_func: softmax
asso_lr_multiplier: 1
attn_constraint: nonneg
attn_lr_multiplier: 0.2
beta: 1
center_lr_multiplier: 1
config_version: hyper0_CPU_general
from_logits: true
lr: 0.15  # 0.03
num_blocks: 32
num_clusters: 8
num_runs: 10
q: 1
r: 2
random_seed: 999
specificity: 0.1  # 0.1
thr: 0
trainable_specificity: false
unsup_rule: threshold
temp: 0.012

# original, too slow. T2-6 dont learn.
# lr=0.1, too slow again, bad order.
# lr=0.3, fast, noisy, bad order.
# lr=0.3, c=0.5, too fast, noisy, bad order

# lr=0.15, slow but going down, bad order.
