Phi: 14.0
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_lr_multiplier: 0.5
beta: 6.0
center_lr_multiplier: 1.0
config_version: hyper1668_sub16_fit-human
from_logits: true
lr: 0.4
num_clusters: 8
num_repetitions: 16
num_subs: 23
q: 1
r: 2
random_seed: 999
specificity: 0.7
temp1: equivalent
temp2: 0.30000000000000004
thr: -0.5
trainable_specificity: false
unsup_rule: threshold
