Phi: 12.0
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_lr_multiplier: 5.0
beta: 0.5
center_lr_multiplier: 1.0
config_version: hyper3510_sub13_fit-human
from_logits: true
lr: 1.2
num_clusters: 8
num_repetitions: 16
num_subs: 23
q: 1
r: 2
random_seed: 999
specificity: 0.1
temp1: equivalent
temp2: -0.08800000000000001
thr: -0.35
trainable_specificity: false
unsup_rule: threshold
