Phi: 10.0
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_lr_multiplier: 5.0
beta: 0.5
center_lr_multiplier: 1.0
config_version: hyper1270_sub13_fit-human
from_logits: true
lr: 0.9
num_clusters: 8
num_repetitions: 16
num_subs: 23
q: 1
r: 2
random_seed: 999
specificity: 0.2
temp1: equivalent
temp2: 0.012
thr: -0.35
trainable_specificity: false
unsup_rule: threshold
