Phi: 10
actv_func: softmax
asso_lr_multiplier: 1
attn_constraint: nonneg
attn_lr_multiplier: 1
beta: 1.25
center_lr_multiplier: 1
config_version: hyper0_CPU_sustain-fullGD-newActvFunc
from_logits: true
lr: 0.09
num_blocks: 32
num_clusters: 8
num_runs: 10
q: 1
r: 2
random_seed: 999
specificity: 0.2
thr: 999.0
trainable_specificity: false
unsup_rule: threshold


# With inhibition
# Phi=10, lr=0.09, c=0.1, speed ok, T2 too close.
#                  c=0.2, speed ok, 
#                  c=0.5, speed ok, noisy later, T2 not so away.