Phi: 12.0
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_lr_multiplier: 5.0
beta: 4.5
center_lr_multiplier: 1.0
config_version: hyper3618_sub20_fit-human
from_logits: true
lr: 0.25
num_clusters: 8
num_repetitions: 16
num_subs: 23
q: 1
r: 2
random_seed: 999
specificity: 0.9
temp1: equivalent
temp2: -0.05
thr: -0.5
trainable_specificity: false
unsup_rule: threshold
