Phi: 5
actv_func: softmax
asso_lr_multiplier: 1
attn_constraint: nonneg
attn_lr_multiplier: 1
beta: 2
center_lr_multiplier: 1
config_version: hyper0_CPU_sustain-fullGD-newActvFunc-inhibition
from_logits: true
lr: 0.05
num_blocks: 32
num_clusters: 8
num_runs: 10
q: 1
r: 2
random_seed: 999
specificity: 0.5
thr: 999.0
trainable_specificity: false
unsup_rule: threshold


# With inhibition
# Phi=10, lr=0.09, c=0.1, speed ok, T2 too close.
#                  c=0.2, speed ok.
#                  c=0.5, speed ok, noisy later, T2 not so away.
#                  c=0.8, speed ok, noisy later, T2 away okish
#                  c=1, T2 away okish, but overall noisy, speed ok.
#                  c=1.5, T2 away okish, but overal noisy and wrong order.

# Phi=10, lr=0.05, c=0.8, speed ok, noisy later, T2 okish
#                  c=0.2, slow, T2,3 too close.

# Phi=10, lr=0.05, c=0.8, beta=5, too fast, order wrong
#                  c=0.8, beta=2, better, too fast, later wrong
# Phi=5, lr=0.05,  c=0.5, beta=2, slow but T2 away.

# Phi=10, lr=0.05, c=0.5, beta=2, better order, T2 too close.
#                         beta=7, fast, wrong order.