Phi: 10.0
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_lr_multiplier: 1.0
beta: 1.0
center_lr_multiplier: 1.0
config_version: hyper1421_double-softmax
from_logits: true
lr: 0.5
num_blocks: 32
num_clusters: 8
num_runs: 10
q: 1
r: 2
random_seed: 999
specificity: 0.55
temp1: 0.5
temp2: 0.012
thr: -0.45
trainable_specificity: false
unsup_rule: threshold
