XY_dir: v3-binary
actv_func: sigmoid
batch_size: 16
binary_loss: BCE
config_version: config_t6.vgg16.block5_pool.1011.run1
epochs: 1000
heldout: '1011'
hyperbolic_strength: null
kernel_constraint: null
kernel_regularizer: null
layer: block5_pool
lr: 0.003
max_shrink_rate: 0.32
meta_seed: 42
min_shrink_rate: 0.25
model_name: vgg16
noise_mode: gaussian
num_locations: 10
num_zooms: 10
patience: 20
preprocessed_dir: v3
rotation_range: 20
run: 1
split_ratio: 0.2
stimulus_set: 6
task: binary
train: finetune
