Phi: 19.0579569393803
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_initializer: ones-withNoise
attn_lr_multiplier: 1.0
attn_positions: block4_pool
attn_regularizer: l1
beta: 4.984413990376332
center_lr_multiplier: 1.0
clustering_config_version: hyper2174_sub14_fit-human-entropy
config_version: config_v4_naive-withNoise
dcnn_config_version: t1.vgg16.block4_pool.None.run1
dcnn_end_actv: null
from_logits: true
high_attn_constraint: sumtoone
high_attn_reg_strength: 0.3
high_attn_regularizer: entropy
inner_loop_epochs: 15
low_attn_constraint: nonneg
lr: 0.7016532519073109
lr_attn: 0.00092
noise_const: null
noise_distribution: uniform
noise_level: 0.4
num_blocks: 32
num_clusters: 8
num_repetitions: 16
num_runs: 500
num_subs: 23
q: 1
r: 2
random_seed: 999
recon_clusters_weighting: 1000000
recon_level: cluster
reg_strength: 0.001
specificity: 0.301403310307209
temp1: equivalent
temp2: 0.29965178138497217
thr: 0.5985481883231338
trainable_specificity: false
unsup_rule: threshold
