Phi: 16.74990436422717
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_initializer: ones-withNoise
attn_lr_multiplier: 2.5
attn_positions: block4_pool
attn_regularizer: l1
beta: 6.30113455256306
center_lr_multiplier: 1.0
clustering_config_version: hyper2667_sub16_fit-human-entropy
config_version: config_v4_naive-withNoise
dcnn_config_version: t1.vgg16.block4_pool.None.run1
dcnn_end_actv: null
from_logits: true
high_attn_constraint: sumtoone
high_attn_reg_strength: 0.005
high_attn_regularizer: entropy
inner_loop_epochs: 15
low_attn_constraint: nonneg
lr: 0.9480284728623583
lr_attn: 0.0006900000000000001
noise_const: null
noise_distribution: uniform
noise_level: 0.5
num_blocks: 32
num_clusters: 8
num_repetitions: 16
num_runs: 500
num_subs: 23
q: 1
r: 2
random_seed: 999
recon_clusters_weighting: 500.0
recon_level: cluster
reg_strength: 0.00075
specificity: 0.5398677093357747
temp1: equivalent
temp2: 0.7161877644017997
thr: 0.6993717159033385
trainable_specificity: false
unsup_rule: threshold
