Phi: 10.0
asso_lr_multiplier: 1.0
attn_lr_multiplier: 1.0
beta: 3.0
center_lr_multiplier: 1.0
clus_actv_func: softmax
config_version: config_v1_naive-withNoise-t1.vgg16.block4_pool.None.run26-with-lowAttn
dcnn_actv_func: sigmoid
dcnn_base: vgg16
dcnn_config_version: config_t1.vgg16.block4_pool.None.run26-with-lowAttn
finetune_run: null
from_logits: true
high_attn_constraint: sumtoone
inner_loop_epochs: 5
layer: block4_pool
low_att_positions: block4_pool
low_attn_constraint: nonneg
low_attn_initializer: ones
low_attn_positions: null
low_attn_regularizer: l1
lr_clus: 0.1
lr_finetune: 0.003
lr_low_attn: 0.00092
noise_distribution: null
noise_level: null
num_blocks: 32
num_clusters: 8
num_runs: 50
q: 1
r: 2
random_seed: 999
recon_clusters_weighting: 1
recon_level: cluster
reg_strength: null
specificity: 0.25
stimulus_set: 1
temp1: equivalent
temp2: 0.012
thr: -0.4
train: finetune-with-lowAttn
trainable_specificity: false
unsup_rule: threshold
