Phi: 10.0
actv_func: softmax
asso_lr_multiplier: 1.0
attn_initializer: ones-withNoise
attn_lr_multiplier: 1.0
attn_positions: block4_pool
attn_regularizer: l1
beta: 3.0
center_lr_multiplier: 1.0
config_version: config_v6a-t0-vgg16_naive-withNoise-entropy
dcnn_config_version: t0.vgg16.block4_pool.None.run1
dcnn_end_actv: false
from_logits: true
high_attn_constraint: sumtoone
high_attn_reg_strength: 0.0001
high_attn_regularizer: entropy
inner_loop_epochs: 5
low_attn_constraint: nonneg
lr: 0.1
lr_attn: 0.00092
noise_const: false
noise_distribution: uniform
noise_level: 0.5
num_blocks: 32
num_clusters: 8
num_runs: 50
q: 1
r: 2
random_seed: 999
recon_clusters_weighting: 1000
recon_level: cluster
reg_strength: 0.1
specificity: 0.25
temp1: equivalent
temp2: 0.012
thr: -0.4
trainable_specificity: false
unsup_rule: threshold
