Phi: 14.0
actv_func: softmax
asso_lr_multiplier: 1.25
attn_constraint: sumtoone
attn_initializer: ones-withNoise
attn_lr_multiplier: 1.25
attn_positions: block4_pool
attn_regularizer: l1
beta: 0.75
center_lr_multiplier: 1.0
clustering_config_version: hyper21008_sub24_fit-human-entropy-nocarryover
config_version: config_v4_naive-withNoise
dcnn_config_version: t1.vgg16.block4_pool.None.run1
dcnn_end_actv: null
from_logits: true
high_attn_constraint: sumtoone
high_attn_reg_strength: 0.375
high_attn_regularizer: entropy
inner_loop_epochs: 5
low_attn_constraint: nonneg
lr: 0.3
lr_attn: 0.0092
noise_const: null
noise_distribution: uniform
noise_level: 0.5
num_blocks: 32
num_clusters: 8
num_repetitions: 16
num_runs: 500
num_subs: 23
q: 1
r: 2
random_seed: 999
recon_clusters_weighting: 100000
recon_level: cluster
reg_strength: 0.001
specificity: 0.625
temp1: equivalent
temp2: 0.5
thr: -0.5
trainable_specificity: false
unsup_rule: threshold
