Phi: 1.689595558458143
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_initializer: ones-withNoise
attn_lr_multiplier: 0.5
attn_positions: block4_pool
attn_regularizer: l1
beta: 6.278604637378268
center_lr_multiplier: 1.0
clustering_config_version: hyper2248_sub05_fit-human
config_version: config_v4_naive-withNoise
dcnn_config_version: t1.vgg16.block4_pool.None.run1
dcnn_end_actv: null
from_logits: true
high_attn_constraint: sumtoone
inner_loop_epochs: 10
low_attn_constraint: nonneg
lr: 0.18634343283907326
lr_attn: 0.092
noise_const: null
noise_distribution: uniform
noise_level: 0.5
num_blocks: 32
num_clusters: 8
num_repetitions: 16
num_runs: 500
num_subs: 23
q: 1
r: 2
random_seed: 999
recon_clusters_weighting: 1000000
recon_level: cluster
reg_strength: 0.001
specificity: 1.661693118112836
temp1: equivalent
temp2: 0.012582808671506776
thr: 0.5593500651093561
trainable_specificity: false
unsup_rule: threshold
